// @generated by scripts/gen-branding.py from branding/nerv.toml - do not edit by hand.

pub const RENDEZVOUS_SERVER: &str = "id.nervcode.eu.org";
pub const RELAY_SERVER: &str = "relay.nervcode.eu.org";
pub const API_SERVER: &str = "https://api.nervcode.eu.org";
pub const RS_PUB_KEY: &str = "HJtH5YUqy6Dz8FHfypUKPJSGoxbBeSgtDsahkT6MBo4=";

/// Seed the client's config defaults with the branded servers and public key.
///
/// `or_insert_with` rather than `insert`: a value already present (a signed custom
/// client read first) must win over this compile-time manifest.
pub fn apply_defaults() {
    let mut defaults = hbb_common::config::DEFAULT_SETTINGS.write().unwrap();
    defaults
        .entry("custom-rendezvous-server".to_owned())
        .or_insert_with(|| RENDEZVOUS_SERVER.to_owned());
    defaults
        .entry("relay-server".to_owned())
        .or_insert_with(|| RELAY_SERVER.to_owned());
    defaults
        .entry("api-server".to_owned())
        .or_insert_with(|| API_SERVER.to_owned());
    defaults
        .entry("key".to_owned())
        .or_insert_with(|| RS_PUB_KEY.to_owned());
}

#[cfg(test)]
mod tests {
    use super::*;
    use hbb_common::{
        config::{Config, RELAY_PORT, RENDEZVOUS_PORT},
        socket_client::check_port,
    };

    #[test]
    fn apply_defaults_seeds_server_options() {
        apply_defaults();
        assert_eq!(
            Config::get_option("custom-rendezvous-server"),
            RENDEZVOUS_SERVER
        );
        assert_eq!(Config::get_option("relay-server"), RELAY_SERVER);
        assert_eq!(Config::get_option("api-server"), API_SERVER);
        assert_eq!(Config::get_option("key"), RS_PUB_KEY);
    }

    #[test]
    fn manifest_hosts_resolve_to_the_standard_ports() {
        apply_defaults();
        assert_eq!(
            Config::get_rendezvous_server(),
            format!("{}:{}", RENDEZVOUS_SERVER, RENDEZVOUS_PORT),
        );
        assert_eq!(
            check_port(RELAY_SERVER, RELAY_PORT),
            format!("{}:{}", RELAY_SERVER, RELAY_PORT),
        );
    }
}
