#!/usr/bin/env python3
"""Generate libs/base/src/branding.rs from branding/nerv.toml.

Paths are resolved relative to this script, so it can be invoked from any CWD:

    python3 scripts/gen-branding.py           # write the generated file
    python3 scripts/gen-branding.py --check   # exit 1 if the file is out of date
"""

from __future__ import annotations

import argparse
import base64
import binascii
import difflib
import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "branding" / "nerv.toml"
OUTPUT = REPO_ROOT / "libs" / "base" / "src" / "branding.rs"

BANNER = (
    "// @generated by scripts/gen-branding.py from branding/nerv.toml - do not edit by hand."
)

REQUIRED_FIELDS = ("id_server", "relay_server", "api_server", "public_key")

# Hostnames, host:port, URLs and base64 all fit this set. It deliberately rejects
# quotes, backslashes and newlines so a manifest value can never break out of the
# Rust string literal it is emitted into.
SAFE_VALUE = re.compile(r"\A[A-Za-z0-9._:/+\-=\[\]%]+\Z")


class ManifestError(Exception):
    pass


def read_manifest() -> dict[str, str]:
    try:
        with MANIFEST.open("rb") as fh:
            data = tomllib.load(fh)
    except FileNotFoundError:
        raise ManifestError(f"manifest not found: {MANIFEST}")
    except tomllib.TOMLDecodeError as err:
        raise ManifestError(f"{MANIFEST} is not valid TOML: {err}")

    server = data.get("server")
    if not isinstance(server, dict):
        raise ManifestError(f"{MANIFEST} has no [server] table")

    values: dict[str, str] = {}
    for field in REQUIRED_FIELDS:
        value = server.get(field)
        if not isinstance(value, str) or not value.strip():
            raise ManifestError(f"[server].{field} is missing, empty or not a string")
        value = value.strip()
        if not SAFE_VALUE.match(value):
            raise ManifestError(
                f"[server].{field} has characters that cannot be emitted into Rust source"
            )
        values[field] = value

    public_key = values["public_key"]
    if len(public_key) != 44:
        raise ManifestError(
            f"[server].public_key must be 44 base64 characters, got {len(public_key)}"
        )
    try:
        decoded = base64.b64decode(public_key, validate=True)
    except (binascii.Error, ValueError) as err:
        raise ManifestError(f"[server].public_key is not valid base64: {err}")
    if len(decoded) != 32:
        raise ManifestError(
            f"[server].public_key must decode to 32 bytes, got {len(decoded)}"
        )

    for field in ("id_server", "relay_server"):
        if values[field].startswith("http") or "/" in values[field]:
            raise ManifestError(
                f"[server].{field} must be a bare host or host:port, got {values[field]!r}"
            )
    if not values["api_server"].startswith(("http://", "https://")):
        raise ManifestError("[server].api_server must start with http:// or https://")

    return values


def expected_with_port(value: str, expr: str, port_const: str) -> str:
    """Rust expression for what the client resolves for this host.

    Mirrors the client, which appends the standard port only when the value has
    no port of its own (`libs/hbb_common/src/config.rs:941-942`,
    `libs/hbb_common/src/socket_client.rs:16`).
    """
    if ":" in value:
        return expr
    return f'format!("{{}}:{{}}", {expr}, {port_const})'


def render(values: dict[str, str]) -> str:
    rendezvous_expected = expected_with_port(
        values["id_server"], "RENDEZVOUS_SERVER", "RENDEZVOUS_PORT"
    )
    relay_expected = expected_with_port(
        values["relay_server"], "RELAY_SERVER", "RELAY_PORT"
    )
    return "\n".join(
        [
            BANNER,
            "",
            f'pub const RENDEZVOUS_SERVER: &str = "{values["id_server"]}";',
            f'pub const RELAY_SERVER: &str = "{values["relay_server"]}";',
            f'pub const API_SERVER: &str = "{values["api_server"]}";',
            f'pub const RS_PUB_KEY: &str = "{values["public_key"]}";',
            "",
            "/// Seed the client's config defaults with the branded servers and public key.",
            "///",
            "/// `or_insert_with` rather than `insert`: a value already present (a signed custom",
            "/// client read first) must win over this compile-time manifest.",
            "pub fn apply_defaults() {",
            "    let mut defaults = hbb_common::config::DEFAULT_SETTINGS.write().unwrap();",
            "    defaults",
            '        .entry("custom-rendezvous-server".to_owned())',
            "        .or_insert_with(|| RENDEZVOUS_SERVER.to_owned());",
            "    defaults",
            '        .entry("relay-server".to_owned())',
            "        .or_insert_with(|| RELAY_SERVER.to_owned());",
            "    defaults",
            '        .entry("api-server".to_owned())',
            "        .or_insert_with(|| API_SERVER.to_owned());",
            "    defaults",
            '        .entry("key".to_owned())',
            "        .or_insert_with(|| RS_PUB_KEY.to_owned());",
            "}",
            "",
            "#[cfg(test)]",
            "mod tests {",
            "    use super::*;",
            "    use hbb_common::{",
            "        config::{Config, RELAY_PORT, RENDEZVOUS_PORT},",
            "        socket_client::check_port,",
            "    };",
            "",
            "    #[test]",
            "    fn apply_defaults_seeds_server_options() {",
            "        apply_defaults();",
            "        assert_eq!(",
            '            Config::get_option("custom-rendezvous-server"),',
            "            RENDEZVOUS_SERVER",
            "        );",
            '        assert_eq!(Config::get_option("relay-server"), RELAY_SERVER);',
            '        assert_eq!(Config::get_option("api-server"), API_SERVER);',
            '        assert_eq!(Config::get_option("key"), RS_PUB_KEY);',
            "    }",
            "",
            "    #[test]",
            "    fn manifest_hosts_resolve_to_the_standard_ports() {",
            "        apply_defaults();",
            "        assert_eq!(",
            "            Config::get_rendezvous_server(),",
            f"            {rendezvous_expected},",
            "        );",
            "        assert_eq!(",
            "            check_port(RELAY_SERVER, RELAY_PORT),",
            f"            {relay_expected},",
            "        );",
            "    }",
            "}",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if libs/base/src/branding.rs is not exactly what this script generates",
    )
    args = parser.parse_args()

    try:
        values = read_manifest()
    except ManifestError as err:
        print(f"gen-branding: error: {err}", file=sys.stderr)
        return 1

    generated = render(values)
    existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else None

    if args.check:
        if existing == generated:
            print(f"gen-branding: {OUTPUT} is up to date")
            return 0
        print(
            f"gen-branding: error: {OUTPUT} is out of date; run scripts/gen-branding.py",
            file=sys.stderr,
        )
        old = existing.splitlines(keepends=True) if existing is not None else []
        sys.stderr.writelines(
            difflib.unified_diff(
                old,
                generated.splitlines(keepends=True),
                fromfile=str(OUTPUT),
                tofile="regenerated",
            )
        )
        return 1

    if existing == generated:
        print(f"gen-branding: {OUTPUT} already up to date")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"gen-branding: wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
